### ISSUE TITLE
Change tagline of subscribe bot

### ISSUE THREAD

**Issue by mmathys** [Daniele122898/ETH-Bot#2]
IMO it would be better if we changed the tagline of the notification from "Subscriber Alert" to something like "Alert: New AlgDat Solution" or "New AlgDat Solution was just released"

That way one would know what came out just by looking at the notification without opening Discord. Now it looks like this: 
![screenshot_20171026-100955](https://user-images.githubusercontent.com/5797176/32041873-0758c89e-ba36-11e7-86ce-deb8f47ba9aa.png)

**Comment by mmathys** [comment]
@Daniele122898

**Comment by Daniele122898** [comment]
And display alert if 2 or more lectures have an alert at the same time. Yeh i think i could do that. Might need some ghetto workarounds tho. Ill test it

**Comment by Daniele122898** [comment]
But im probably not going to differentiate solutions and exercise and just focus on the lecture itself since that makes everything easier especially if sol + ex are published simultaniously like in todays lin alg

**Comment by mmathys** [comment]
Nice :)

**Comment by Daniele122898** [comment]
I'm going to release this untested and pray that it works. should be online in about 1-2 hours. If the alerts seem to function properly im going to close this 👍
